In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('data\online_retail_II.xlsx')
df.head()

Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12   
1  489434    79323P                   PINK CHERRY LIGHTS        12   
2  489434    79323W                  WHITE CHERRY LIGHTS        12   
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48   
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24   

          InvoiceDate  Price  Customer ID         Country  
0 2009-12-01 07:45:00   6.95      13085.0  United Kingdom  
1 2009-12-01 07:45:00   6.75      13085.0  United Kingdom  
2 2009-12-01 07:45:00   6.75      13085.0  United Kingdom  
3 2009-12-01 07:45:00   2.10      13085.0  United Kingdom  
4 2009-12-01 07:45:00   1.25      13085.0  United Kingdom

In [3]:
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [4]:
df.shape

(1048575, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype         
---  ------       --------------    -----         
 0   Invoice      1048575 non-null  object        
 1   StockCode    1048575 non-null  object        
 2   Description  1044203 non-null  object        
 3   Quantity     1048575 non-null  int64         
 4   InvoiceDate  1048575 non-null  datetime64[ns]
 5   Price        1048575 non-null  float64       
 6   Customer ID  811893 non-null   float64       
 7   Country      1048575 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 64.0+ MB


In [6]:
# remove rows with null Customer IDs
df = df[df['Customer ID' ].notna()]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 811893 entries, 0 to 1048574
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   Invoice      811893 non-null  object        
 1   StockCode    811893 non-null  object        
 2   Description  811893 non-null  object        
 3   Quantity     811893 non-null  int64         
 4   InvoiceDate  811893 non-null  datetime64[ns]
 5   Price        811893 non-null  float64       
 6   Customer ID  811893 non-null  float64       
 7   Country      811893 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 55.7+ MB


In [7]:
#convert Costomer ID data type from float to integer
df['Customer ID'] = df['Customer ID'].astype('int')
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             int32
Country                object
dtype: object

In [8]:
df.head()

Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12   
1  489434    79323P                   PINK CHERRY LIGHTS        12   
2  489434    79323W                  WHITE CHERRY LIGHTS        12   
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48   
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24   

          InvoiceDate  Price  Customer ID         Country  
0 2009-12-01 07:45:00   6.95        13085  United Kingdom  
1 2009-12-01 07:45:00   6.75        13085  United Kingdom  
2 2009-12-01 07:45:00   6.75        13085  United Kingdom  
3 2009-12-01 07:45:00   2.10        13085  United Kingdom  
4 2009-12-01 07:45:00   1.25        13085  United Kingdom

In [9]:
df['Country'].value_counts()

United Kingdom          730115
Germany                  17327
EIRE                     15910
France                   13972
Netherlands               5054
Spain                     3740
Switzerland               3064
Belgium                   3056
Portugal                  2450
Australia                 1913
Channel Islands           1658
Italy                     1526
Norway                    1382
Sweden                    1343
Cyprus                    1176
Finland                   1048
Austria                    931
Denmark                    806
Greece                     627
Japan                      574
Poland                     535
Unspecified                524
USA                        503
United Arab Emirates       386
Singapore                  346
Israel                     324
Malta                      299
Iceland                    242
Canada                     228
Lithuania                  189
RSA                        123
Brazil                      94
Thailand

In [10]:
df[df.Quantity<=0]

Invoice StockCode                     Description  Quantity  \
178      C489449     22087        PAPER BUNTING WHITE LACE       -12   
179      C489449    85206A    CREAM FELT EASTER EGG BASKET        -6   
180      C489449     21895   POTTING SHED SOW 'N' GROW SET        -4   
181      C489449     21896              POTTING SHED TWINE        -6   
182      C489449     22083      PAPER CHAIN KIT RETRO SPOT       -12   
...          ...       ...                             ...       ...   
1046566  C580313     22649    STRAWBERRY FAIRY CAKE TEAPOT        -3   
1046567  C580313     22419                LIPSTICK PEN RED        -6   
1046568  C580313     22303        COFFEE MUG APPLES DESIGN        -2   
1046569  C580313     21232  STRAWBERRY CERAMIC TRINKET POT        -3   
1047708  C580392    84247E  PACK OF 12 CHRISTMAS FUN CARDS       -12   

                InvoiceDate  Price  Customer ID         Country  
178     2009-12-01 10:33:00   2.95        16321       Australia  
179     2009-12-01 10:33:00   1.65        16321       Australia  
180     2009-12-01 10:33:00   4.25        16321       Australia  
181     2009-12-01 10:33:00   2.10        16321       Australia  
182     2009-12-01 10:33:00   2.95        16321       Australia  
...                     ...    ...          ...             ...  
1046566 2011-12-02 15:10:00   4.95        12668         Germany  
1046567 2011-12-02 15:10:00   0.42        12668         Germany  
1046568 2011-12-02 15:10:00   2.55        12668         Germany  
1046569 2011-12-02 15:10:00   1.25        12668         Germany  
1047708 2011-12-04 10:46:00   2.95        16283  United Kingdom  

[18513 rows x 8 columns]

In [11]:
df[df.Invoice.str.startswith('C') == 1]

Invoice StockCode                     Description  Quantity  \
178      C489449     22087        PAPER BUNTING WHITE LACE       -12   
179      C489449    85206A    CREAM FELT EASTER EGG BASKET        -6   
180      C489449     21895   POTTING SHED SOW 'N' GROW SET        -4   
181      C489449     21896              POTTING SHED TWINE        -6   
182      C489449     22083      PAPER CHAIN KIT RETRO SPOT       -12   
...          ...       ...                             ...       ...   
1046566  C580313     22649    STRAWBERRY FAIRY CAKE TEAPOT        -3   
1046567  C580313     22419                LIPSTICK PEN RED        -6   
1046568  C580313     22303        COFFEE MUG APPLES DESIGN        -2   
1046569  C580313     21232  STRAWBERRY CERAMIC TRINKET POT        -3   
1047708  C580392    84247E  PACK OF 12 CHRISTMAS FUN CARDS       -12   

                InvoiceDate  Price  Customer ID         Country  
178     2009-12-01 10:33:00   2.95        16321       Australia  
179     2009-12-01 10:33:00   1.65        16321       Australia  
180     2009-12-01 10:33:00   4.25        16321       Australia  
181     2009-12-01 10:33:00   2.10        16321       Australia  
182     2009-12-01 10:33:00   2.95        16321       Australia  
...                     ...    ...          ...             ...  
1046566 2011-12-02 15:10:00   4.95        12668         Germany  
1046567 2011-12-02 15:10:00   0.42        12668         Germany  
1046568 2011-12-02 15:10:00   2.55        12668         Germany  
1046569 2011-12-02 15:10:00   1.25        12668         Germany  
1047708 2011-12-04 10:46:00   2.95        16283  United Kingdom  

[18513 rows x 8 columns]

In [12]:
#check whether the invoice numbers always start with 'C' wherever the negative quantities occur
set(df[df.Invoice.str.startswith('C') == 1].index) - set(df[df.Quantity<=0].index)

set()

In [13]:
set(df[df.Quantity<=0].index) - set(df[df.Invoice.str.startswith('C') == 1].index)

set()

Conclusion: all the rows with negative quantity have the Invoices start with 'C' which may stand for cancelation

In [14]:
negative_quantity_df = df[df.Quantity<=0]
negative_quantity_df.head()

Invoice StockCode                    Description  Quantity  \
178  C489449     22087       PAPER BUNTING WHITE LACE       -12   
179  C489449    85206A   CREAM FELT EASTER EGG BASKET        -6   
180  C489449     21895  POTTING SHED SOW 'N' GROW SET        -4   
181  C489449     21896             POTTING SHED TWINE        -6   
182  C489449     22083     PAPER CHAIN KIT RETRO SPOT       -12   

            InvoiceDate  Price  Customer ID    Country  
178 2009-12-01 10:33:00   2.95        16321  Australia  
179 2009-12-01 10:33:00   1.65        16321  Australia  
180 2009-12-01 10:33:00   4.25        16321  Australia  
181 2009-12-01 10:33:00   2.10        16321  Australia  
182 2009-12-01 10:33:00   2.95        16321  Australia

In [15]:
negative_quantity_df.tail()

Invoice StockCode                     Description  Quantity  \
1046566  C580313     22649    STRAWBERRY FAIRY CAKE TEAPOT        -3   
1046567  C580313     22419                LIPSTICK PEN RED        -6   
1046568  C580313     22303        COFFEE MUG APPLES DESIGN        -2   
1046569  C580313     21232  STRAWBERRY CERAMIC TRINKET POT        -3   
1047708  C580392    84247E  PACK OF 12 CHRISTMAS FUN CARDS       -12   

                InvoiceDate  Price  Customer ID         Country  
1046566 2011-12-02 15:10:00   4.95        12668         Germany  
1046567 2011-12-02 15:10:00   0.42        12668         Germany  
1046568 2011-12-02 15:10:00   2.55        12668         Germany  
1046569 2011-12-02 15:10:00   1.25        12668         Germany  
1047708 2011-12-04 10:46:00   2.95        16283  United Kingdom

In [16]:
negative_quantity_df.Invoice.str.len().unique()

array([7], dtype=int64)

In [17]:
negative_quantity_df['InvoiceNum'] = negative_quantity_df.Invoice.str.slice(1).astype('int')
negative_quantity_df.dtypes

<ipython-input-17-c901707239a0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negative_quantity_df['InvoiceNum'] = negative_quantity_df.Invoice.str.slice(1).astype('int')


Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             int32
Country                object
InvoiceNum              int32
dtype: object

In [18]:
negative_quantity_df.head()

Invoice StockCode                    Description  Quantity  \
178  C489449     22087       PAPER BUNTING WHITE LACE       -12   
179  C489449    85206A   CREAM FELT EASTER EGG BASKET        -6   
180  C489449     21895  POTTING SHED SOW 'N' GROW SET        -4   
181  C489449     21896             POTTING SHED TWINE        -6   
182  C489449     22083     PAPER CHAIN KIT RETRO SPOT       -12   

            InvoiceDate  Price  Customer ID    Country  InvoiceNum  
178 2009-12-01 10:33:00   2.95        16321  Australia      489449  
179 2009-12-01 10:33:00   1.65        16321  Australia      489449  
180 2009-12-01 10:33:00   4.25        16321  Australia      489449  
181 2009-12-01 10:33:00   2.10        16321  Australia      489449  
182 2009-12-01 10:33:00   2.95        16321  Australia      489449

In [19]:
positive_quantity_df = df[df.Quantity > 0]
positive_quantity_df.shape, positive_quantity_df.dtypes

((793380, 8),
 Invoice                object
 StockCode              object
 Description            object
 Quantity                int64
 InvoiceDate    datetime64[ns]
 Price                 float64
 Customer ID             int32
 Country                object
 dtype: object)

In [20]:
positive_quantity_df['InvoiceNum'] = positive_quantity_df.Invoice.astype('int')
positive_quantity_df.dtypes

<ipython-input-20-f5b7e7528b4d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  positive_quantity_df['InvoiceNum'] = positive_quantity_df.Invoice.astype('int')


Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             int32
Country                object
InvoiceNum              int32
dtype: object

In [21]:
df[df['Customer ID']==16321]

Invoice StockCode                         Description  Quantity  \
178     C489449     22087            PAPER BUNTING WHITE LACE       -12   
179     C489449    85206A        CREAM FELT EASTER EGG BASKET        -6   
180     C489449     21895       POTTING SHED SOW 'N' GROW SET        -4   
181     C489449     21896                  POTTING SHED TWINE        -6   
182     C489449     22083          PAPER CHAIN KIT RETRO SPOT       -12   
183     C489449     21871                 SAVE THE PLANET MUG       -12   
184     C489449     84946     ANTIQUE SILVER TEA GLASS ETCHED       -12   
185     C489449    84970S   HANGING HEART ZINC T-LIGHT HOLDER       -24   
186     C489449     22090           PAPER BUNTING RETRO SPOTS       -12   
187      489450     22087            PAPER BUNTING WHITE LACE        12   
188      489450    85206A        CREAM FELT EASTER EGG BASKET         6   
189      489450     21895       POTTING SHED SOW 'N' GROW SET         4   
190      489450     21896                  POTTING SHED TWINE         6   
191      489450     22083          PAPER CHAIN KIT RETRO SPOT        12   
192      489450     21871                 SAVE THE PLANET MUG        12   
193      489450     84946     ANTIQUE SILVER TEA GLASS ETCHED        12   
194      489450    84970S   HANGING HEART ZINC T-LIGHT HOLDER        24   
195      489450     22090           PAPER BUNTING RETRO SPOTS        12   
135099   502275    85206A        CREAM FELT EASTER EGG BASKET        12   
135100   502275     22585           PACK OF 6 BIRDY GIFT TAGS        12   
590070   541657     22087            PAPER BUNTING WHITE LACE         6   
590071   541657    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
590072   541657     21056               DOCTOR'S BAG SOFT TOY         3   
590073   541657     22960            JAM MAKING SET WITH JARS         6   
609731   543372     22087            PAPER BUNTING WHITE LACE        18   
609732   543372     22325              MOBILE VINTAGE HEARTS          3   
609760  C543375     22325              MOBILE VINTAGE HEARTS         -3   
609761  C543375     22087            PAPER BUNTING WHITE LACE       -18   
609762   543376     22325              MOBILE VINTAGE HEARTS          3   
609763   543376     22087            PAPER BUNTING WHITE LACE        18   
890392   568687     22090             PAPER BUNTING RETROSPOT        12   
890393   568687     21198        WHITE HEART CONFETTI IN TUBE        24   
890539  C568694     22090             PAPER BUNTING RETROSPOT       -12   
890540  C568694     21198        WHITE HEART CONFETTI IN TUBE       -24   
890541   568695     22090             PAPER BUNTING RETROSPOT        12   
890542   568695     21198        WHITE HEART CONFETTI IN TUBE        24   

               InvoiceDate  Price  Customer ID    Country  
178    2009-12-01 10:33:00   2.95        16321  Australia  
179    2009-12-01 10:33:00   1.65        16321  Australia  
180    2009-12-01 10:33:00   4.25        16321  Australia  
181    2009-12-01 10:33:00   2.10        16321  Australia  
182    2009-12-01 10:33:00   2.95        16321  Australia  
183    2009-12-01 10:33:00   1.25        16321  Australia  
184    2009-12-01 10:33:00   1.25        16321  Australia  
185    2009-12-01 10:33:00   0.85        16321  Australia  
186    2009-12-01 10:33:00   2.95        16321  Australia  
187    2009-12-01 10:36:00   2.95        16321  Australia  
188    2009-12-01 10:36:00   1.65        16321  Australia  
189    2009-12-01 10:36:00   4.25        16321  Australia  
190    2009-12-01 10:36:00   2.10        16321  Australia  
191    2009-12-01 10:36:00   2.95        16321  Australia  
192    2009-12-01 10:36:00   1.25        16321  Australia  
193    2009-12-01 10:36:00   1.25        16321  Australia  
194    2009-12-01 10:36:00   0.85        16321  Australia  
195    2009-12-01 10:36:00   2.95        16321  Australia  
135099 2010-03-23 16:01:00   1.65        16321  Australia  
135100 2010-03-23 16:01:00   1.2

Observations for orders from the Customer with ID 16321: The cancelations came before or at the same time when the orders were placed.

In [22]:
df[df['Customer ID']==12668].tail(60)

Invoice StockCode                          Description  Quantity  \
659550    547822     22979              PANTRY WASHING UP BRUSH        12   
659551    547822     22982                  PANTRY PASTRY BRUSH        12   
659552    547822     22993         SET OF 4 PANTRY JELLY MOULDS        12   
659553    547822     23078             ICE CREAM PEN LIP GLOSS         24   
659554    547822     23179           CLOCK MAGNET MUM'S KITCHEN         6   
659555    547822     20750             RED RETROSPOT MINI CASES         2   
659556    547822     22962                JAM JAR WITH PINK LID        12   
659557    547822     22467                    GUMBALL COAT RACK         6   
659558    547822     22221      CAKE STAND LOVEBIRD 2 TIER PINK         2   
659559    547822     22215       CAKE STAND WHITE TWO TIER LACE         2   
659560    547822     37500          TEA TIME TEAPOT IN GIFT BOX        12   
659561    547822     22123                 PING MICROWAVE APRON        12   
659562    547822     22062  CERAMIC BOWL WITH LOVE HEART DESIGN        36   
659563    547822     37501         TEA TIME TEA SET IN GIFT BOX        12   
659564    547822      POST                              POSTAGE        16   
671294   C548915     22993         SET OF 4 PANTRY JELLY MOULDS       -12   
671295   C548915     22329   ROUND CONTAINER SET OF 5 RETROSPOT       -12   
1031119   579094     20750             RED RETROSPOT MINI CASES         2   
1031120   579094     21481           FAWN BLUE HOT WATER BOTTLE         4   
1031121   579094     21165        BEWARE OF THE CAT METAL SIGN         12   
1031122   579094     22939            ADULT APRON APPLE DELIGHT         4   
1031123   579094    47567B               TEA TIME KITCHEN APRON         3   
1031124   579094     21035      SET/2 RED RETROSPOT TEA TOWELS          6   
1031125   579094     22895  SET OF 2 TEA TOWELS APPLE AND PEARS         6   
1031126   579094     21218               RED SPOTTY BISCUIT TIN         6   
1031127   579094     22199             FRYING PAN RED RETROSPOT         4   
1031128   579094     21154            RED RETROSPOT OVEN GLOVE         10   
1031129   579094    47559B                  TEA TIME OVEN GLOVE        10   
1031130   579094     22720    SET OF 3 CAKE TINS PANTRY DESIGN          3   
1031131   579094     23115         RED APPLES CHOPPING BOARD            3   
1031132   579094     23114        VINTAGE LEAF CHOPPING BOARD           3   
1031133   579094     23113                PANTRY CHOPPING BOARD         3   
1031134   579094     23244       ROUND STORAGE TIN VINTAGE LEAF         6   
1031135   579094     21531         RED RETROSPOT SUGAR JAM BOWL         6   
1031136   579094     21535         RED RETROSPOT SMALL MILK JUG         6   
1031137   579094     21533             RETROSPOT LARGE MILK JUG         3   
1031138   579094     21232       STRAWBERRY CERAMIC TRINKET POT        24   
1031139   579094     22064           PINK DOUGHNUT TRINKET POT         12   
1031140   579094     37450    CERAMIC CAKE BOWL + HANGING CAKES         6   
1031141   579094     20914  SET/5 RED RETROSPOT LID GLASS BOWLS         6   
1031142   579094     22303             COFFEE MUG APPLES DESIGN        12   
1031143   579094     22302             COFFEE MUG PEARS  DESIGN        12   
1031144   579094     22059        CERAMIC STRAWBERRY DESIGN MUG        12   
1031145   579094     37448      CERAMIC CAKE DESIGN SPOTTED MUG        12   
1031146   579094     22894        TABLECLOTH RED APPLES DESIGN          2   
1031147   579094     22649         STRAWBERRY FAIRY CAKE TEAPOT        16   
1031148   579094     23445                    ICE CREAM BUBBLES        20   
1031149   579094     22419                     LIPSTICK PEN RED        12   
1031150   579094     22644       CERAMIC CHERRY CAKE MONEY BANK        12   
1031151   579094     48185                   DOORMAT FAIRY CAKE         4   
1031152   579094     22326  ROUND SNACK BOXES SET OF4 WOODLAND          6   
10311

Observations for orders from the Customer with ID 12668: NO orders were placed before cancelation.

In [23]:
set(positive_quantity_df['InvoiceNum']).intersection(set(negative_quantity_df['InvoiceNum'])) 

set()

Conclusion: No orders were placed before order cancelation. So, we'll remove all the rows with negative quantity.

In [24]:
online_retail_clean = positive_quantity_df.drop('Invoice', axis=1)
online_retail_clean.dtypes

StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             int32
Country                object
InvoiceNum              int32
dtype: object

In [25]:
uk_online_retail_clean = online_retail_clean[online_retail_clean.Country=='United Kingdom']
uk_online_retail_clean.shape

(714291, 8)

In [26]:
online_retail_clean.to_excel('data\online_retail_clean.xlsx')

In [27]:
uk_online_retail_clean.to_excel('data\\uk_online_retail_clean.xlsx')